server:
  port: 8082


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.fonix.colab.entity
spring:
  mvc:
    view:
      suffix: .html
    static-path-pattern:   /**
  web:
    resources:
      static-locations: classpath:/static/
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/coLab?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

jwt:
  secret: f4e2e52034348f86b67cde581c0f9eb5
  expire: 604800
  header: token

